//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicaLog.Web.MusicaLogService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MusicaLogService.IMusicaLogService")]
    public interface IMusicaLogService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicaLogService/GetMusicaLogs", ReplyAction="http://tempuri.org/IMusicaLogService/GetMusicaLogsResponse")]
        MusicaLog.Common.Models.MusicaLog[] GetMusicaLogs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicaLogService/GetMusicaLogs", ReplyAction="http://tempuri.org/IMusicaLogService/GetMusicaLogsResponse")]
        System.Threading.Tasks.Task<MusicaLog.Common.Models.MusicaLog[]> GetMusicaLogsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicaLogService/GetMusicaLog", ReplyAction="http://tempuri.org/IMusicaLogService/GetMusicaLogResponse")]
        MusicaLog.Common.Models.MusicaLog GetMusicaLog(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicaLogService/GetMusicaLog", ReplyAction="http://tempuri.org/IMusicaLogService/GetMusicaLogResponse")]
        System.Threading.Tasks.Task<MusicaLog.Common.Models.MusicaLog> GetMusicaLogAsync(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicaLogService/AddMusicaLog", ReplyAction="http://tempuri.org/IMusicaLogService/AddMusicaLogResponse")]
        int AddMusicaLog(MusicaLog.Common.Models.MusicaLog musicaLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicaLogService/AddMusicaLog", ReplyAction="http://tempuri.org/IMusicaLogService/AddMusicaLogResponse")]
        System.Threading.Tasks.Task<int> AddMusicaLogAsync(MusicaLog.Common.Models.MusicaLog musicaLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicaLogService/UpdateMusicaLog", ReplyAction="http://tempuri.org/IMusicaLogService/UpdateMusicaLogResponse")]
        int UpdateMusicaLog(MusicaLog.Common.Models.MusicaLog musicaLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicaLogService/UpdateMusicaLog", ReplyAction="http://tempuri.org/IMusicaLogService/UpdateMusicaLogResponse")]
        System.Threading.Tasks.Task<int> UpdateMusicaLogAsync(MusicaLog.Common.Models.MusicaLog musicaLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicaLogService/DeleteMusicaLog", ReplyAction="http://tempuri.org/IMusicaLogService/DeleteMusicaLogResponse")]
        int DeleteMusicaLog(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicaLogService/DeleteMusicaLog", ReplyAction="http://tempuri.org/IMusicaLogService/DeleteMusicaLogResponse")]
        System.Threading.Tasks.Task<int> DeleteMusicaLogAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMusicaLogServiceChannel : MusicaLog.Web.MusicaLogService.IMusicaLogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MusicaLogServiceClient : System.ServiceModel.ClientBase<MusicaLog.Web.MusicaLogService.IMusicaLogService>, MusicaLog.Web.MusicaLogService.IMusicaLogService {
        
        public MusicaLogServiceClient() {
        }
        
        public MusicaLogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MusicaLogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MusicaLogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MusicaLogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MusicaLog.Common.Models.MusicaLog[] GetMusicaLogs() {
            return base.Channel.GetMusicaLogs();
        }
        
        public System.Threading.Tasks.Task<MusicaLog.Common.Models.MusicaLog[]> GetMusicaLogsAsync() {
            return base.Channel.GetMusicaLogsAsync();
        }
        
        public MusicaLog.Common.Models.MusicaLog GetMusicaLog(System.Nullable<int> id) {
            return base.Channel.GetMusicaLog(id);
        }
        
        public System.Threading.Tasks.Task<MusicaLog.Common.Models.MusicaLog> GetMusicaLogAsync(System.Nullable<int> id) {
            return base.Channel.GetMusicaLogAsync(id);
        }
        
        public int AddMusicaLog(MusicaLog.Common.Models.MusicaLog musicaLog) {
            return base.Channel.AddMusicaLog(musicaLog);
        }
        
        public System.Threading.Tasks.Task<int> AddMusicaLogAsync(MusicaLog.Common.Models.MusicaLog musicaLog) {
            return base.Channel.AddMusicaLogAsync(musicaLog);
        }
        
        public int UpdateMusicaLog(MusicaLog.Common.Models.MusicaLog musicaLog) {
            return base.Channel.UpdateMusicaLog(musicaLog);
        }
        
        public System.Threading.Tasks.Task<int> UpdateMusicaLogAsync(MusicaLog.Common.Models.MusicaLog musicaLog) {
            return base.Channel.UpdateMusicaLogAsync(musicaLog);
        }
        
        public int DeleteMusicaLog(int id) {
            return base.Channel.DeleteMusicaLog(id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteMusicaLogAsync(int id) {
            return base.Channel.DeleteMusicaLogAsync(id);
        }
    }
}
